version: 2
updates:
  - package-ecosystem: gomod
    directory: /operator
    schedule:
      interval: weekly
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"

  - package-ecosystem: gomod
    directory: /go-agent
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /tests/functional
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directories:
      - /operator
      - /go-agent
      - /dmtcp
    schedule:
      interval: weekly
