//go:build !ignore_autogenerated

// Code generated by hand following controller-gen conventions. DO NOT EDIT
// unless the API types change (controller-gen was not available in the build
// environment; regenerate with controller-gen object paths=./... if installed).

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *WorkloadReference) DeepCopyInto(out *WorkloadReference) {
	*out = *in
}

// DeepCopy creates a new WorkloadReference.
func (in *WorkloadReference) DeepCopy() *WorkloadReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *PlacementLabel) DeepCopyInto(out *PlacementLabel) {
	*out = *in
}

// DeepCopy creates a new PlacementLabel.
func (in *PlacementLabel) DeepCopy() *PlacementLabel {
	if in == nil {
		return nil
	}
	out := new(PlacementLabel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *MigratableWorkloadSpec) DeepCopyInto(out *MigratableWorkloadSpec) {
	*out = *in
	out.WorkloadRef = in.WorkloadRef
	if in.PlacementLabel != nil {
		in, out := &in.PlacementLabel, &out.PlacementLabel
		*out = new(PlacementLabel)
		**out = **in
	}
	if in.ProcessMigration != nil {
		in, out := &in.ProcessMigration, &out.ProcessMigration
		*out = new(bool)
		**out = **in
	}
	if in.VolumeMigration != nil {
		in, out := &in.VolumeMigration, &out.VolumeMigration
		*out = new(bool)
		**out = **in
	}
	if in.PreSyncRounds != nil {
		in, out := &in.PreSyncRounds, &out.PreSyncRounds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy creates a new MigratableWorkloadSpec.
func (in *MigratableWorkloadSpec) DeepCopy() *MigratableWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(MigratableWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *RegisteredPod) DeepCopyInto(out *RegisteredPod) {
	*out = *in
	if in.RegisteredAt != nil {
		in, out := &in.RegisteredAt, &out.RegisteredAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy creates a new RegisteredPod.
func (in *RegisteredPod) DeepCopy() *RegisteredPod {
	if in == nil {
		return nil
	}
	out := new(RegisteredPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *MigratableWorkloadStatus) DeepCopyInto(out *MigratableWorkloadStatus) {
	*out = *in
	if in.RegisteredPods != nil {
		in, out := &in.RegisteredPods, &out.RegisteredPods
		*out = make([]RegisteredPod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new MigratableWorkloadStatus.
func (in *MigratableWorkloadStatus) DeepCopy() *MigratableWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(MigratableWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *MigratableWorkload) DeepCopyInto(out *MigratableWorkload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a new MigratableWorkload.
func (in *MigratableWorkload) DeepCopy() *MigratableWorkload {
	if in == nil {
		return nil
	}
	out := new(MigratableWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generically typed copy of the receiver.
func (in *MigratableWorkload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *MigratableWorkloadList) DeepCopyInto(out *MigratableWorkloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MigratableWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new MigratableWorkloadList.
func (in *MigratableWorkloadList) DeepCopy() *MigratableWorkloadList {
	if in == nil {
		return nil
	}
	out := new(MigratableWorkloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generically typed copy of the receiver.
func (in *MigratableWorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *MigrationSpec) DeepCopyInto(out *MigrationSpec) {
	*out = *in
}

// DeepCopy creates a new MigrationSpec.
func (in *MigrationSpec) DeepCopy() *MigrationSpec {
	if in == nil {
		return nil
	}
	out := new(MigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *MigrationStatus) DeepCopyInto(out *MigrationStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new MigrationStatus.
func (in *MigrationStatus) DeepCopy() *MigrationStatus {
	if in == nil {
		return nil
	}
	out := new(MigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *Migration) DeepCopyInto(out *Migration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a new Migration.
func (in *Migration) DeepCopy() *Migration {
	if in == nil {
		return nil
	}
	out := new(Migration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generically typed copy of the receiver.
func (in *Migration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *MigrationList) DeepCopyInto(out *MigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Migration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new MigrationList.
func (in *MigrationList) DeepCopy() *MigrationList {
	if in == nil {
		return nil
	}
	out := new(MigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generically typed copy of the receiver.
func (in *MigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
