apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mosquitto-app
spec:
  selector:
    matchLabels:
      app: mosquitto-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mosquitto-app
    spec:
      volumes:
      - name: dmtcp-shared
        emptyDir: {}
      initContainers:
      - name: dmtcp-init
        image: mycedrive/dmtcp:dev
        command: ["sh", "-c", "cp -r /share/. /dmtcp/ && echo 'DMTCP binaries ready'"]
        volumeMounts:
        - name: dmtcp-shared
          mountPath: /dmtcp
      containers:
      - name: mosquitto
        image: prrsjunior/mosquitto:arq1
        ports:
        - containerPort: 9001
        - containerPort: 1883
        env:
        - name: MIGR_COOR         # hostname to reach the MC REST API
          value: mycedrive.mig-ready.svc.cluster.local
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: START_UP          # Application startup command wrapped by DMTCP
          value: "/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf"
        - name: DMTCP_COORD_HOST
          value: "127.0.0.1"
        - name: DMTCP_CHECKPOINT_DIR
          value: /dmtcp/checkpoints
        volumeMounts:             # Shared volume with DMTCP binaries
        - name: dmtcp-shared
          mountPath: /dmtcp
        lifecycle:
          preStop:
            exec:
              # end_container calls /remove and /copy on the MC
              command:
                - /dmtcp/bin/end_container
                - mycedrive.mig-ready.svc.cluster.local
                - $(POD_NAME)
                - /dmtcp/checkpoints
      - name: dmtcp
        image: mycedrive/dmtcp:dev
        ports:
        - containerPort: 7779
        env:
        - name: DMTCP_CHECKPOINT_DIR
          value: /dmtcp/checkpoints
        volumeMounts:             # Shared volume with the DMTCP binaries
        - name: dmtcp-shared
          mountPath: /share
